[package]
name = "simple-tween"
version = "0.0.1"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.16.0"
strum_macros = "0.16.0"
typename = "0.1.1"
serde = { version = "1.0.101", features = ["derive"] }

